### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by bjornwahman** [roboticsound/Pulsarr#3]
Hi, Thanks for this addon. Im behind a https reverse proxy using letsencrypt certificate.
I cant figure out how to setup pulsarr with it.
My radarr have the url: https://myhost.com/radarr
is there support for this setup?
Thank you

**Comment by roboticsound** [comment]
Hmm maybe not I will take a look this weekend.

**Comment by bjornwahman** [comment]
I have tried 
Host: https://myhost.com/radarr
Port: empty
Api key: XXXXXXXX

Host: https://myhost.com/radarr
Port: 443
Api key: XXXXXXXX

Host: myhost.com/radarr
Port: 443
Api key: XXXXXXXX

Host: http://myhost.com/radarr
Port: 443
Api key: XXXXXXXX

I am happy to test and help in any way possible :)

**Comment by roboticsound** [comment]
@bjornwahman I am hoping this is now fixed, though I don't have a reverse proxy set up so I am hoping that you are able to test. Are you able to download zip from github and test with your setup?

**Comment by bjornorri** [comment]
@roboticsound It appears that it is not fixed.

I'm experiencing the same problem with the same setup (reverse proxy and SSL).

**Comment by roboticsound** [comment]
Did you download the latest version from github?

**Comment by bjornorri** [comment]
I just blindly assumed the latest version was deployed, my bad. Pulled and tried it and it worked fine 👍

For the record I used the following options format:
Host: https://myhost.com/radarr
Port: empty
Api key: XXXXXXXX

**Comment by roboticsound** [comment]
Ok good, I will push this out in a minor release tomorrow. Thanks for trying it out.

**Comment by desimaniac** [comment]
Thanks @bjornorri and @roboticsound. 

Would like to add for that for reverse proxy (i.e. nginx) with subdomains, to leave the port empty as well:
host: https://radarr.domain.com
port: empty
basic authentication: username/password
api key: xxx
